#!/bin/bash

Password="daniel0519";

echo "Escrito por Daniel A. Torquato para bash."

unset opt;

while [ "$opt" != "0" ]
do

menu=( 
	"Exit" 
	"Criar disciplina" 
	"Adicionar tarefa" 
	"Mostras tarefas" 
	"Alterar tarefas" )

# Caso uma tarefa seja adicionada para a agenda de uma disciplina tambem deve
# ser adicionada no cronograma geral


	echo "Organizador: "
	for i in $(seq 1 ${#menu[*]})
	do
		echo "$(($i-1))) ${menu[$i-1]} "
	done
	echo -n "myshell >> "

	read opt;

	if [ "$opt" == "1" ]; then
		echo -n "Qual o nome da disciplina: ";
		read dic;
		mkdir -p $DIC/$dic;
		mysql -u $USER --password=$Password -e \
		"use $Periodo; 
		create table if not exists $dic 
		(compromissos varchar(256), deadline datetime);"

	elif [ "$opt" == "2" ]; then 

		echo -n "Escolha uma disciplina: ";

		# Lista todas as disciplinas no banco de dados
		unset disciplinas;
		while read line
		do
			disciplinas+=("$line")
		done < <(mysql -u $USER --password=$Password $Periodo -se "show tables")

		for i in $(seq 1 ${#disciplinas[*]}); do
			echo "$i) ${disciplinas[$i-1]}";
		done

		read dic;

		echo -n \
"Qual o compromisso a ser adicionado? 
myshell >> "
		read compromisso;
		echo -n \
"Qual a data limite para entrega? [ano-mes-dia hora:minuto]:
myshell >> "
		read deadline;

		mysql -u $USER --password=$Password -se \
		"use $Periodo; 
		insert into ${disciplinas[$dic-1]} (compromissos, deadline)
		values ('$compromisso','$deadline')"
	elif [ "$opt" == "3" ]
	then
		echo "Qual a disciplina deve ser mostrada? "
		unset disciplinas;
		while read line
		do
			disciplinas+=("$line")
		done < <(mysql -u $USER --password=$Password $Periodo -se "show tables")

		echo "0) Todas "
		for i in $(seq 1 ${#disciplinas[*]}); do
			echo "$i) ${disciplinas[$i-1]}";
		done
		echo -n "myshell >> "
		read dic;
		if [ $dic -gt 0 ]
		then
			mysql -u $USER --password=$Password -e \
			"use $Periodo;
			 select * from ${disciplinas[$dic-1]};"
		elif [ "$dic" == 0 ]
		then
			mysql -u $USER --password=$Password -e \
			"use Org;
			 select * from ano;" 
		fi
	elif [ "$opt" == "4" ]
	then
		echo "De qual disciplina é a materia? "
		unset disciplinas;
		while read line
		do
			disciplinas+=("$line")
		done < <(mysql -u $USER --password=$Password $Periodo -se "show tables")

		echo "0) Ano "
		for i in $(seq 1 ${#disciplinas[*]}); do
			echo "$i) ${disciplinas[$i-1]}";
		done
		echo -n "myshell >> "
		if [ $dic -gt 0 ]
		then
			mysql -u $USER --password=$Password -e \
			"use $Periodo;
			 select * from ${disciplinas[$dic-1]};"
		elif [ "$dic" == 0 ]
		then
			mysql -u $USER --password=$Password -e \
			"use Org;
			 select * from ano;" 
		fi





#		mysql -u $USER --password=$Password -e \
#		"use Org;
#		 select * from ${disciplinas[$dic-1]};"
	fi



done
