#!/bin/bash

Org=$Documents/Organizacao
Periodo=10P;
P=$Org/$Periodo;
DIC=$P/dic;
DICs=(`ls $DIC`);

echo -n "Abrir arquivo de organização[s/n]:"
read x;

if [ "$x" == "s" ]; then
	inkscape $P/org.svg &
fi

echo "Escolha a  disciplina: "

for i in $(seq 1 ${#DICs[@]})
do
	echo "$i) ${DICs[$i-1]}"
done
echo -n ">> ";
read n;

if [ "$n" == "0" ]; then
	return;
fi

cd $DIC/${DICs[$(($n-1))]};

